//
// Created by ldh on 20-8-12.
//

#ifndef CATKIN_WS_SRC_LOCAL_PLANNER_COMMON_INCLUDE_QUINTIC_POLYNOMIAL_HPP_
#define CATKIN_WS_SRC_LOCAL_PLANNER_COMMON_INCLUDE_QUINTIC_POLYNOMIAL_HPP_

#endif //CATKIN_WS_SRC_LOCAL_PLANNER_COMMON_INCLUDE_QUINTIC_POLYNOMIAL_HPP_
