@startuml

class BehavoiurPlanner{
   -std::unique_ptr<BehavoirStrategy> behaviour_strategy
   +BehavoiurPlanner(const std::string& type)
   #Process(const TrajectoryPoint& init_point, Behaviour& behaviour):bool
 }

abstract class BehavoirStrategy{
  {abstract} + Execute(const TrajectoryPoint& init_point, Behaviour& behaviour) :bool;
}

class MDPMPlanner{
  +MDPMPlanner()
}

class EDUMPlanner{
  +EDUMPlanner()

}
class FSMPlanner{
 +FSMPlanner()
}
FSMPlanner--->BehavoirStrategy
MDPMPlanner--->BehavoirStrategy
EDUMPlanner--->BehavoirStrategy
BehavoiurPlanner....>FSMPlanner
BehavoiurPlanner....> MDPMPlanner
BehavoiurPlanner....> EDUMPlanner
BehavoiurPlanner o----BehavoirStrategy
@enduml