
#ifndef PLANNING_ALGORITHM_SRC_FRENET_LATTICE_PLANNER_INCLUDE_FRENET_LATTICE_PLANNER_END_CONDITION_SAMPLER_HPP_
#define PLANNING_ALGORITHM_SRC_FRENET_LATTICE_PLANNER_INCLUDE_FRENET_LATTICE_PLANNER_END_CONDITION_SAMPLER_HPP_
#include <ros/ros.h>
namespace planning{
class EndConditionsSampler{
public:
    EndConditionsSampler();
    ~EndConditionsSampler();
    bool SampleEndCondition();
private:

};
}

#endif //PLANNING_ALGORITHM_SRC_FRENET_LATTICE_PLANNER_INCLUDE_FRENET_LATTICE_PLANNER_END_CONDITION_SAMPLER_HPP_
