uint8 type

uint8 NONE = 1
uint8 DRIVING = 2
uint8 STOP = 3
uint8 SHOULDER = 4
uint8 BIKING = 5
uint8 SIDEWALK = 6
uint8 BORDER = 7
uint8 RESTRICTED = 8
uint8 PARKING = 9
uint8 BIDIRECTIONAL = 10
uint8 MEDIAN = 11
uint8 SPECIAL1 = 12
uint8 SPECIAL2 = 13
uint8 SPECIAL3 = 14
uint8 ROADWORKS = 15
uint8 TRAM = 16
uint8 RAIL = 17
uint8 ENTRY = 18
uint8 EXIT = 19
uint8 OFFRAMP = 20
uint8 ONRAMP = 21
uint8 ANY = 22
